config/routes.rb
SocialHelpApp::Application.routes.draw do

  resources :proposals
  resources :project_reports, only: [:index, :create] do
    member do
      put 'approve'
      put 'reject'
    end
  end

  resources :issues do
    member do
      put "change_status"
    end
    collection do
      get "interested_ngos"
      get "pending_issues"
      get "completed_issues"
    end
  end

  resources :fiscal_stats
  resources :projects do
    collection do
      get 'completed_projects'
      get 'pending_proposed_projects'
      get 'ongoing_projects'
      get 'reject_project'
      get 'project_reports'
      get 'pending_fund'
      get 'fund_log'
    end
    member do
      get 'close_project'
      post 'release_fund'
    end
  end

  resource :users, only: [:edit] do
    collection do
      patch "update_profile"
      post "change_image"
      get 'user_profile'
    end
  end
  devise_for :users, controllers: {registrations: "sign_up", sessions: "sessions"}

  get "profile" => "users#profile"
  get "dashboard" => "users#dashboard"
  get "my_projects" => "users#my_projects"
  get "welfare_funds" => "users#welfare_funds"
  get "my_proposals" => "proposals#my_proposals"
  get "my_issues" => "issues#my_issues"
  get "donate" => "users#donate"
  post "receive_donation" => "users#receive_donation"
  get "my_donations" => "users#my_donations"
  get "reject_proposal" => "proposals#reject_proposal"
  get "view_donations" => "users#view_donations"
  root to: "users#home"

end

app/models/fiscal_stat.rb
class FiscalStat < ActiveRecord::Base
	belongs_to :user

	after_create :update_kitty_fund, if: :eligible?

	validate :one_record_per_fiscal_year_per_company


	private

	def eligible?
		self.eligibility_status
	end

	def one_record_per_fiscal_year_per_company
		fis_stat = FiscalStat.where(fiscal_year: self.fiscal_year, user_id: self.user_id).first
		if fis_stat.present?
			self.errors.add :base, "Record For Given Financial Year Is Already Present"
		end
	end

	def update_kitty_fund
		# calculate the social_fund for company based of net profit
		calculated_value = self.net_profit * Constants::SOCIALFUND_RATIO
		self.update_attribute(:available_social_fund, calculated_value.to_f)

		# insert of update(if exist) social_funds's total_kitty_fund for a particular year based on companies fund
		social_fund = SocialFund.where(fiscal_year: self.fiscal_year).first
		# if present then will update kitty fund else will create new record
		if social_fund.present?
			case self.pref_cat
			when "Others", ""
				social_fund.fund_for_others += self.available_social_fund
			when "Children"
				social_fund.fund_for_children += self.available_social_fund
			when "Disabled"
				social_fund.fund_for_disabled += self.available_social_fund
			when "Education"
				social_fund.fund_for_education += self.available_social_fund
			when "Elderly"
				social_fund.fund_for_elderly += self.available_social_fund
			when "Employment"
				social_fund.fund_for_employment += self.available_social_fund
			when "Environment"
				social_fund.fund_for_environment += self.available_social_fund
			when "Health"
				social_fund.fund_for_health += self.available_social_fund
			when "Women"
				social_fund.fund_for_women += self.available_social_fund			
			when "Youth"
				social_fund.fund_for_youth += self.available_social_fund			
			end			
			social_fund.total_kitty_fund += self.available_social_fund
			social_fund.fund_remains += self.available_social_fund
			social_fund.save
		else
			# check for remaining balance of the previous year
			prev_social_fund = SocialFund.where(fiscal_year: self.fiscal_year - 1).first
			kitty_value = self.available_social_fund
			edu_value = self.pref_cat == "Education" ? self.available_social_fund : 0
			child_value = self.pref_cat == "Children" ? self.available_social_fund : 0
			women_value = self.pref_cat == "Women" ? self.available_social_fund : 0
			eld_value = self.pref_cat == "Elderly" ? self.available_social_fund : 0
			env_value = self.pref_cat == "Environment" ? self.available_social_fund : 0
			emp_value = self.pref_cat == "Employment" ? self.available_social_fund : 0
			othr_value = (self.pref_cat == "Others" || self.pref_cat == "")  ? self.available_social_fund : 0
			youth_value = self.pref_cat == "Youth" ? self.available_social_fund : 0
			dis_value = self.pref_cat == "Disabled" ? self.available_social_fund : 0
			hlt_value = self.pref_cat == "Health" ? self.available_social_fund : 0

			if prev_social_fund && prev_social_fund.fund_remains > 0
				kitty_value += prev_social_fund.fund_remains
				edu_value += prev_social_fund.fund_for_education
				child_value += prev_social_fund.fund_for_children
				women_value += prev_social_fund.fund_for_women
				eld_value += prev_social_fund.fund_for_elderly
				env_value += prev_social_fund.fund_for_environment
				emp_value += prev_social_fund.fund_for_employment
				othr_value += prev_social_fund.fund_for_others
				youth_value += prev_social_fund.fund_for_youth
				dis_value += prev_social_fund.fund_for_disabled
				hlt_value += prev_social_fund.fund_for_health																																			
			end
			SocialFund.create(fiscal_year: self.fiscal_year, total_kitty_fund: kitty_value, fund_remains: kitty_value, 
				fund_for_education: edu_value, fund_for_children: child_value, fund_for_women: women_value, fund_for_elderly: eld_value,
				fund_for_environment: env_value, fund_for_employment: emp_value, fund_for_others: othr_value, fund_for_youth: youth_value, 
				fund_for_disabled: dis_value, fund_for_health: hlt_value)
		end
	end
end

app/controllers/fiscal_stats_controller.rb
class FiscalStatsController < ApplicationController
  before_action :set_fiscal_stat, only: [:show, :edit, :update, :destroy] 

  # GET /fiscal_stats
  # GET /fiscal_stats.json
  def index
    @fiscal_stats = FiscalStat.all.where(user_id: current_user.id)
    params[:nav] = "list_fiscal_stats"
  end

  # GET /fiscal_stats/1
  # GET /fiscal_stats/1.json
  def show
  end

  # GET /fiscal_stats/new
  def new
    @fiscal_stat = FiscalStat.new()
    params[:nav] = "add_fiscal_stat"
  end

  # GET /fiscal_stats/1/edit
  def edit
  end

  # POST /fiscal_stats
  # POST /fiscal_stats.json
  def create
    @fiscal_stat = FiscalStat.new(issue_params)
    @fiscal_stat.user_id = current_user.id
    @fiscal_stat.eligibility_status = true if @fiscal_stat.net_profit.to_i >= Constants::ELIGIBILITY_CRITERIA
    
    respond_to do |format|
      if @fiscal_stat.save
        format.html { redirect_to @fiscal_stat, notice: 'Fiscal stat was successfully created.' }
        format.json { render action: 'show', status: :created, location: @fiscal_stat }
      else
        format.html { render action: 'new' }
        format.json { render json: @fiscal_stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fiscal_stats/1
  # PATCH/PUT /fiscal_stats/1.json
  def update
    respond_to do |format|
      if @fiscal_stat.update(issue_params)
        format.html { redirect_to @fiscal_stat, notice: 'Fiscal stat was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @fiscal_stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fiscal_stats/1
  # DELETE /fiscal_stats/1.json
  def destroy
    @fiscal_stat.destroy
    respond_to do |format|
      format.html { redirect_to fiscal_stats_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fiscal_stat
      @fiscal_stat = FiscalStat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fiscal_stat_params
      params[:fiscal_stat]
    end

    def issue_params
      params.require(:fiscal_stat).permit(:fiscal_year, :currency_type, :total_revenue, :net_profit, :available_social_fund, :user_id, :eligibility_status, :pref_cat)
    end
end

app/helpers/fiscal_stats_helper.rb
module FiscalStatsHelper
end

app/views/fiscal_stats/_form.html.erb
<%= form_for(@fiscal_stat, html: {class: "form-horizontal"}) do |f| %>
  <% if @fiscal_stat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fiscal_stat.errors.count, "error") %> prohibited this fiscal_stat from being saved:</h2>

      <ul>
      <% @fiscal_stat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :fiscal_year,"Financial Year", class: "control-label" %>
    <div class='controls'><%= f.select(:fiscal_year, options_for_select(Constants::FISCAL_YEAR,(@fiscal_stat.fiscal_year.present? ? params[:fiscal_stat][:fiscal_year] : nil)), prompt: "Select Period") %></div>
  </div>
  <div class="control-group">
    <%= f.label :total_revenue,"Total Revenue", class: "control-label" %>
    <div class='controls'><%= f.text_field :total_revenue %></div>
  </div>
  <div class="control-group">
    <%= f.label :net_profit,"Net Profit", class: "control-label" %>
    <div class='controls'><%= f.text_field :net_profit %></div>
  </div>
  <div class="control-group">
    <%= f.label :currency_type,"Currency Type", class: "control-label" %>
    <div class='controls'><%= f.select(:currency_type, options_for_select(Constants::VALID_CURRENCIES), prompt: "Select Currency") %></div>
  </div>
  <div class="control-group">
    <%= f.label :pref_cat,"Prefered Category", class: "control-label" %>
    <div class='controls'><%= f.select(:pref_cat, options_for_select(Constants::IssueCategoryConstant.to_list), prompt: "Select Category") %></div>
  </div>

  <div class="ml-180">
    <%= f.submit "Save", class: "btn btn-primary"%>
  </div>
<% end %>

app/views/fiscal_stats/edit.html.erb
<div class="row-fluid">
	<div class="span3">
		<%= render "navs/corp_left_panel"%>
	</div>

	<div class="panel-sign-in span9"  style="margin-top: 40px;">
		<div class="panel-heading-sign-in">
			<h4>Edit Finance Stats</h4>
		</div>
		<div class="panel-body-sign-in">
			<div class="form-wrapper">
				<%= render 'form' %>
			</div>
		</div>
	</div>
</div>

app/views/fiscal_stats/index.html.erb
<div class="row-fluid">
  <div class="span3">
    <%= render "navs/corp_left_panel"%>
  </div>

  <div class="panel-sign-in span9"  style="margin-top: 40px;">
    <div class="panel-heading-sign-in">
      <h4>Financial Stats of <%= "#{current_user.name}" %></h4>
    </div>
    <div class="panel-body-sign-in">
      <%if @fiscal_stats.present?%>
        <table class="table">
          <thead>
            <th>Financial Year</th>
            <th>Total Revenue</th>
            <th>Net Profit</th>
            <th>Currency Type</th>
            <th>Eligibility</th>
            <th>Social Fund(<%= (Constants::SOCIALFUND_RATIO * 100).to_i %>%)</th>
            <th></th>
          </thead>
          <tbody>
            <% @fiscal_stats.each do |fiscal_stat| %>
              <tr>
                <% f_y = fiscal_stat.fiscal_year.to_s.concat("-#{fiscal_stat.fiscal_year + 1}") %>
                <td><%= f_y %></td>
                <td><%= fiscal_stat.total_revenue %></td>
                <td><%= fiscal_stat.net_profit %></td>
                <td><%= fiscal_stat.currency_type %></td>
                <td><%= fiscal_stat.eligibility_status ? "Yes" : "No" %></td>     
                <td><%= fiscal_stat.eligibility_status ? fiscal_stat.available_social_fund : "N/A" %></td>
                <td><%= link_to 'View', fiscal_stat, class: "btn btn-primary" %></td>
                <!--<td><%#= link_to 'Edit', edit_fiscal_stat_path(fiscal_stat), class: "btn btn-primary" %></td> -->
                <!--<td><%#= link_to 'Destroy', fiscal_stat, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
              </tr>
            <% end %>
          </tbody>
        </table>
      <%else%>
        <p>No Detail Available For Financial year(s)</p>
      <%end%>
    </div>
  </div>
</div>

app/views/fiscal_stats/new.html.erb
<div class="row-fluid">
	<div class="span3">
		<%= render "navs/corp_left_panel"%>
	</div>

	<div class="panel-sign-in span9"  style="margin-top: 40px;">
		<div class="panel-heading-sign-in">
			<h4>Create Finance Stats</h4>
		</div>
		<div class="panel-body-sign-in">
			<div class="form-wrapper">
				<%= render 'form' %>
			</div>
		</div>
	</div>
</div>

app/views/fiscal_stats/show.html.erb
<div class="row-fluid">
	<div class="span3">
		<%= render "navs/corp_left_panel"%>
	</div>
	<% f_y = @fiscal_stat.fiscal_year.to_s.concat("-#{@fiscal_stat.fiscal_year + 1}")%>
	<div class="panel-sign-in span9"  style="margin-top: 40px;">
		<div class="panel-heading-sign-in">
			<h4>Details For Financial Year <%= f_y %></h4>
		</div>
		<div class="panel-body-sign-in">
			<table class="table">
				<thead>
					<th></th>
					<th><th>
				</thead>
				<tbody>
					<tr>
						<th>Financial Year</th>
						<td><%= f_y %></td>
					</tr>
					<tr>
						<th>Total Revenue</th>
						<td><%= @fiscal_stat.total_revenue %></td>
					</tr>
					<tr>
						<th>Net Profit</th>
						<td><%= @fiscal_stat.net_profit %></td>
					</tr>
					<tr>
						<th>Eligibility</th>
						<td><%= @fiscal_stat.eligibility_status ? "Yes" : "No" %></td>
					</tr>
					<tr>
						<th>Currency Type</th>
						<td><%= @fiscal_stat.currency_type %></td>
					</tr>
					<tr>
						<th>Social Fund(<%= (Constants::SOCIALFUND_RATIO * 100).to_i %>%)</th>
						<td><%= @fiscal_stat.eligibility_status ? @fiscal_stat.available_social_fund : "N/A"%></td>
					</tr>
				</tbody>
			</table>
		</div>
		<div class="panel-body-sign-in">
			<%= link_to 'back', fiscal_stats_path %>
		</div>
	</div>
</div>