config/routes.rb
SocialHelpApp::Application.routes.draw do

  resources :proposals
  resources :project_reports, only: [:index, :create] do
    member do
      put 'approve'
      put 'reject'
    end
  end

  resources :issues do
    member do
      put "change_status"
    end
    collection do
      get "interested_ngos"
      get "pending_issues"
      get "completed_issues"
    end
  end

  resources :fiscal_stats
  resources :projects do
    collection do
      get 'completed_projects'
      get 'pending_proposed_projects'
      get 'ongoing_projects'
      get 'reject_project'
      get 'project_reports'
      get 'pending_fund'
      get 'fund_log'
    end
    member do
      get 'close_project'
      post 'release_fund'
    end
  end

  resource :users, only: [:edit] do
    collection do
      patch "update_profile"
      post "change_image"
      get 'user_profile'
    end
  end
  devise_for :users, controllers: {registrations: "sign_up", sessions: "sessions"}

  get "profile" => "users#profile"
  get "dashboard" => "users#dashboard"
  get "my_projects" => "users#my_projects"
  get "welfare_funds" => "users#welfare_funds"
  get "my_proposals" => "proposals#my_proposals"
  get "my_issues" => "issues#my_issues"
  get "donate" => "users#donate"
  post "receive_donation" => "users#receive_donation"
  get "my_donations" => "users#my_donations"
  get "reject_proposal" => "proposals#reject_proposal"
  get "view_donations" => "users#view_donations"
  root to: "users#home"

end

app/models/project.rb
class Project < ActiveRecord::Base

	belongs_to :user
	has_many :project_reports
	has_many :project_funds
	
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.includes(:user).find_by(id: params[:id])
    @reports = ProjectReport.includes(:project_fund).where(project_id: params[:id]).order("updated_at DESC")
    @fund_release = 0
    @percent_done = 0
    @reports.each do |p|
      if p.fund_release
        @fund_release += p.project_fund.fund_amount
        @percent_done = p.percent_done > @percent_done ? p.percent_done : @percent_done
      end
    end
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    issue = Issue.find_by(id: params[:project][:issue_id].to_i)
    @project = Project.new
    @project.project_name = issue.issue_title
    @project.project_type = issue.category
    @project.area = issue.issue_area
    @project.project_actual_cost = params[:project][:project_actual_cost].to_i
    @project.assigned_by = current_user.id
    @project.verified_by = current_user.id
    @project.user_id = params[:project][:user_id].to_i
    @project.verified = true
    @project.project_status = Constants::ProjectStatusConstant.all_to_hash[:in_progress]
    @project.project_duration = params[:project][:project_duration].to_i
    @project.proposer_id = issue.user_id
    @project.issue_id = issue.id
    @project.est_completion_date = (Date.today + (30 * @project.project_duration.to_i).days).to_date
    @project.save

    proposal = Proposal.find_by(id: params[:project][:prop_id])
    proposal.update(status: Constants::ProposalStatusConstant.all_to_hash[:approved])

    render json: {status: 500, prop_id: params[:project][:prop_id]}
  end

  def ongoing_projects
    if params["spec"].present? && params["spec"] == "true"
      @ongoing_projects = Project.where(project_status: Constants::ProjectStatusConstant.all_to_hash[:in_progress], verified: true, proposer_id: current_user.id)
    else
  	  @ongoing_projects = Project.where(project_status: Constants::ProjectStatusConstant.all_to_hash[:in_progress], verified: true)
    end
    params[:cat] = "on_projects"
  end

  def completed_projects
    if params["spec"].present? && params["spec"] == "true"
      @projects = Project.where(project_status: Constants::ProjectStatusConstant.all_to_hash[:completed], verified: true, proposer_id: current_user.id)
    else
  	  @projects = Project.where(project_status: Constants::ProjectStatusConstant.all_to_hash[:completed], verified: true )
    end
    params[:cat] = "comp_projects"
  end

  def reject_project
  	issue = Issue.where(id: params[:issue_id]).first
  	issue.update(issue_status: Constants::IssueStatusConstant.all_to_hash[:rejected], rejected_on: Date.today, rejected_by: current_user.id)
    render json: {status: 500, iss_id: params[:issue_id]}
  end

  def close_project
    @project = Project.find(params[:id])
    @issue = Issue.find_by_id(params[:issue_id])
		respond_to do |format|
			if @project.update_attributes(project_status: Constants::ProjectStatusConstant.all_to_hash[:completed], closed_by: current_user.id, closed_on: Date.today)
        @issue.update(issue_status: Constants::IssueStatusConstant.all_to_hash[:completed], closed_by: current_user.id, closed_on: Date.today)
				format.html { redirect_to dashboard_path, notice: 'Project was successfully completed.' }
				format.json { head :no_content }
			else
				format.html { render action: 'edit' }
				format.json { render json: @project.errors, status: :unprocessable_entity }
			end
		end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  def pending_fund
    @pending_reports = ProjectReport.includes(project: [:user]).where(status: "approved", fund_release: false)
    params[:cat] = "fund_release"
  end

  def release_fund
    res = ProjectFund.release_fund(params[:id], current_user)
    render json: res
  end

  def fund_log
    @fund_log = ProjectFundLog.includes(project: [:user]).order("created_at desc").load
    params[:cat] = "fund_log"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:project_name, :project_type, :area, :project_est_cost, :project_actual_cost, :est_start_date, :actual_start_date, :est_completion_date, :actual_completion_date, :assigned_to, :assigned_by, :verified_by, :closed_by, :project_duration, :verified, :project_status, :user_id, :issue_id, :closed_on, :approved_on)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<link rel="stylesheet" href="/assets/bootstrap-datetimepicker.min.css">
<script src="/assets/bootstrap-datetimepicker.min.js"></script>
<div class="panel-body-sign-in">
  <div class="form-wrapper">
		<%= form_for(@project, html: {class: "form-horizontal"}) do |f| %>
			<% if @project.errors.any? %>
				<div id="error_explanation">
					<h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>
					<ul>
						<% @project.errors.full_messages.each do |msg| %>
							<li><%= msg %></li>
						<% end %>
					</ul>
				</div>
			<% end %>

			<div class="control-group">
			  <%= f.label :project_name,"", class: "control-label" %>
			  <div class="controls">
			  	<%= f.text_field :project_name %>
			  </div>
			</div>

			<div class="control-group">
			  <%= f.label :project_type,"", class: "control-label" %>
			  <div class="controls">
			  	<%= f.text_field :project_type %>
			  </div>
			</div>

			<div class="control-group">
			  <%= f.label :area,"", class: "control-label" %>
			  <div class="controls">
			  	<%= f.text_field :area %>
			  </div>
			</div>

			<div class="control-group">
			  <%= f.label :project_est_cost,"", class: "control-label" %>
			  <div class="controls">
			  	<%= f.text_field :project_est_cost, onkeypress: "return isNumber(event)" %>
			  </div>
			</div>

			<div class="control-group">
			  <%= f.label :project_actual_cost,"", class: "control-label" %>
			  <div class="controls">
			  	<%= f.text_field :project_actual_cost, onkeypress: "return isNumber(event)" %>
			  </div>
			</div>

			<div class="control-group">
			  <%= f.label :est_start_date,"", class: "control-label" %>
			  <div class="controls">
  				<div id="datetimepicker1" class="input-append date">
    				<input name="est_start_date" data-format="dd/MM/yyyy" type="text"></input>
    				<span class="add-on">
	      			<i data-time-icon="icon-time" data-date-icon="icon-calendar" class="icon-calendar" >
	      			</i>
    				</span>
  				</div>
				</div>
			</div>

			<div class="control-group">
			  <%= f.label :actual_start_date,"", class: "control-label" %>
			  <div class="controls">
			  	<div id="datetimepicker2" class="input-append date">
    				<input name="actual_start_date" data-format="dd/MM/yyyy" type="text"></input>
    				<span class="add-on">
	      			<i data-time-icon="icon-time" data-date-icon="icon-calendar" class="icon-calendar" >
	      			</i>
    				</span>
  				</div>
			  </div>
			</div>

			<div class="control-group">
			  <%= f.label :est_completion_date,"", class: "control-label" %>
			  <div class="controls">
			  	<div id="datetimepicker3" class="input-append date">
    				<input name="est_completion_date" data-format="dd/MM/yyyy" type="text"></input>
    				<span class="add-on">
	      			<i data-time-icon="icon-time" data-date-icon="icon-calendar" class="icon-calendar" >
	      			</i>
    				</span>
  				</div>
			  </div>
			</div>

			<div class="control-group">
			  <%= f.label :actual_completion_date,"", class: "control-label" %>
			  <div class="controls">
			  	<div id="datetimepicker4" class="input-append date">
    				<input name="actual_completion_date" data-format="dd/MM/yyyy" type="text"></input>
    				<span class="add-on">
	      			<i data-time-icon="icon-time" data-date-icon="icon-calendar" class="icon-calendar" >
	      			</i>
    				</span>
  				</div>
			  </div>
			</div>

			<div class="control-group">
			  <%= f.label :assigned_to,"", class: "control-label" %>
			  <div class="controls">
			  	<%= f.select(:assigned_to, options_for_select(User.where(role: "NGO").map{|x| [x.name, x.id]}, { prompt: "Select NGO"})) %>
			  </div>
			</div>

			<div class="control-group">
			  <%= f.label :project_duration,"", class: "control-label" %>
			  <div class="controls">
			  	<%= f.text_field :project_duration %>
			  </div>
			</div>

			<div class="control-group">
			  <%= f.label :verified,"", class: "control-label" %>
			  <div class="controls">
			  	<%= f.check_box :verified %>
			  </div>
			</div>

			<div class="actions">
			  <%= f.submit %>
			  <%= link_to 'Back', profile_path, class: 'btn btn-primary' %>
			  <% if params[:controller] == "users" && (params[:action] == "edit" or params[:action] == "update")%>
			  	<%= link_to 'Show', projects_path(@project.id), class: 'btn btn-primary' %>
			  <% end %>
			</div>
		<% end %>
	</div>
</div>

<script>
	jQuery(function($) {
    $( "#datetimepicker1" ).datetimepicker({
    	pickTime: false
    });
    $( "#datetimepicker2" ).datetimepicker({
    	pickTime: false
    });
    $( "#datetimepicker3" ).datetimepicker({
    	pickTime: false
    });
    $( "#datetimepicker4" ).datetimepicker({
    	pickTime: false
    });
  });
</script>

app/views/projects/_project_list.html.erb
<% if @projects.present? %>
	<div class="scrollit">
		<table class="table">
			<thead>
				<th>S. No.</th>
				<th>Project name</th>
				<th>Project type</th>
				<th>Area</th>
				<th>Project est cost</th>
				<th>Est start date</th>
				<th>Est completion date</th>
				<th>Assigned to</th>
				<th>Assigned by</th>
				<th>Verified by</th>
				<th>Closed by</th>
				<th>Verification Status</th>
				<th>Project Status</th>
				<th>Project duration</th>
				<th colspan="3">Actions</th>
			</thead>
			<tbody>
				<% @projects.each_with_index do |project,i| %>
					<tr>
						<td><%= i + 1 %></td>
						<td><%= project.project_name %></td>
						<td><%= project.project_type %></td>
						<td><%= project.area %></td>
						<td><%= project.project_est_cost %></td>
						<td><%= project.est_start_date %></td>
						<td><%= project.est_completion_date %></td>
						<td><%= User.fetch_user_names(project.user_id) %></td>
						<td><%= User.fetch_user_names(project.assigned_by) %></td>
						<td><%= User.fetch_user_names(project.verified_by) %></td>
						<td><%= User.fetch_user_names(project.closed_by) %></td>
						<td><%= project.verified ? "Verified" : "Not Verified" %></td>
						<td><%= project.project_status %></td>
						<td><%= project.project_duration %></td>
						<td><%= link_to "View", project_path(id: project.id), class: "btn btn-primary" %></td>
						<% if project.project_status == "In Progress" && current_user.role == "Analyst"%>
							<td><%= link_to "Edit", edit_project_path(id: project.id), class: "btn btn-warning" %></td>
							<td><%= link_to "Close Project", close_project_project_path(id: project.id), data: { confirm: 'Are you sure?' }, class: "btn btn-warning" %></td>
						<% end %>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
<% else %>
	<% if @comp %>
		<p>No completed project(s).</p>
	<% else %>
		<p>No project(s) created yet.</p>
	<% end %>
<% end %>

app/views/projects/completed_projects.html.erb
<div class="row-fluid">
	<div class="span3">
		<%= render_panel(current_user.role) %>
	</div>

	<div class="span9"  style="margin-top: 40px;">
		<div class="row">
			<div class="col-xs-12">
				<div class="table-header">
					Completed Projects
				</div>
				<div class="table-responsive">
					<div id="sample-table-2_wrapper" class="dataTables_wrapper" role="grid">
						<table id="sample-table-2" class="table table-striped table-bordered table-hover dataTable" aria-describedby="sample-table-2_info">
							<thead>
								<tr role="row">
									<th class="sorting" role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1" aria-label="" style="width: 80px;">S. No.</th>
									<th class="sorting" role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1" aria-label="" style="width: 180px;">Project Name</th>
									<th class="sorting" role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1" aria-label="" style="width: 210px;">Project Type</th>
									<th class="sorting" role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1" aria-label="" style="width: 118px;">Area</th>
									<th class="sorting" role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1" aria-label="" style="width: 110px;">Cost</th>
									<th class="sorting" role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1" aria-label="" style="width: 100px;">Start Date</th>
									<th class="sorting" role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1" aria-label="" style="width: 100px;">Completion Date</th>
									<th class="sorting" role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1" aria-label="" style="width: 145px;">Assigned To</th>
									<th class="sorting" role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1" aria-label="" style="width: 145px;">Project Duration</th>
									<th class="" role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1" aria-label="" style="width: 120px;"></th>
								</tr>
							</thead>
							<tbody role="alert" aria-live="polite" aria-relevant="all">
								<% @projects.each_with_index do |project,i| %>
									<tr>
										<td><%= i + 1 %></td>
										<td><%= project.project_name %></td>
										<td><%= project.project_type %></td>
										<td><%= project.area %></td>
										<td><%= project.project_actual_cost %></td>
										<td><%= project.created_at.to_date.to_s %></td>
										<td><%= project.actual_completion_date %></td>
										<td><%= User.fetch_user_names(project.user_id) %></td>
										<td><%= project.project_duration %> Month(s)</td>
										<td>
											<div class="visible-md visible-lg hidden-sm hidden-xs btn-group">
												<a href="<%= project_path(id: project.id) %>" class="btn btn-xs btn-info" data-rel="tooltip" title="" data-original-title="Show Project"><i class="icon-eye-open bigger-120"></i></a>
											</div>
										</td>
									</tr>
								<% end %>
							</tbody>
						</table>
					</div>
				</div>
				<% unless @projects.present? %>
					<div class="col-xs-12" style="width: 100%;text-align: center;background-color: #F3E1C2;">
						<strong>No Completed project(s)</strong>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>
<script>
	$(function(){
		$("[data-rel='tooltip']").tooltip();
	})
</script>

app/views/projects/edit.html.erb
<div class="row-fluid">
	<div class="span3">
		<%= render_panel(current_user.role) %>
	</div>
	<div class="panel-sign-in span9">
		<div class="panel-heading-sign-in">
			<h4>Editing Project: </h4><%= @project.project_name %>
		</div>
		<%= render 'form' %>
	</div>
</div>

app/views/projects/ongoing_projects.html.erb
<div class="row-fluid">
	<div class="span3">
		<%= render_panel(current_user.role) %>
	</div>

	<div class="span9"  style="margin-top: 40px;">
		<div class="row">
			<div class="col-xs-12">
				<div class="table-header">
					Projects in Progress
				</div>
				<div class="table-responsive">
					<div id="sample-table-2_wrapper" class="dataTables_wrapper" role="grid">
						<table id="sample-table-2" class="table table-striped table-bordered table-hover dataTable" aria-describedby="sample-table-2_info">
							<thead>
								<tr role="row">
									<th class="sorting" role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1" aria-label="" style="width: 80px;">S. No.</th>
									<th class="sorting" role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1" aria-label="" style="width: 180px;">Project Name</th>
									<th class="sorting" role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1" aria-label="" style="width: 210px;">Project Type</th>
									<th class="sorting" role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1" aria-label="" style="width: 118px;">Area</th>
									<th class="sorting" role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1" aria-label="" style="width: 110px;">Cost</th>
									<th class="sorting" role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1" aria-label="" style="width: 145px;">Assigned To</th>
									<th class="sorting" role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1" aria-label="" style="width: 145px;">Project Duration</th>
									<th class="" role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1" aria-label="" style="width: 120px;"></th>
								</tr>
							</thead>
							<tbody role="alert" aria-live="polite" aria-relevant="all">
								<% @ongoing_projects.each_with_index do |project,i| %>
									<tr>
										<td><%= i + 1 %></td>
										<td><%= project.project_name %></td>
										<td><%= project.project_type %></td>
										<td><%= project.area %></td>
										<td><%= project.project_actual_cost %></td>
										<td><%= User.fetch_user_names(project.user_id) %></td>
										<td><%= project.project_duration %> Month(s)</td>
										<td>
											<div class="visible-md visible-lg hidden-sm hidden-xs btn-group">
												<a href="<%= project_path(id: project.id) %>" class="btn btn-xs btn-info" data-rel="tooltip" title="" data-original-title="Show Project"><i class="icon-eye-open bigger-120"></i></a>
												<% if current_user.inspector? %>
													<a href="<%= edit_project_path(id: project.id) %>" class="btn btn-xs btn-danger"  data-rel="tooltip" title="" data-original-title="Edit Project"><i class="icon-edit bigger-120"></i></a>
												<% end %>
											</div>
										</td>
									</tr>
								<% end %>
							</tbody>
						</table>
					</div>
				</div>
				<% unless @ongoing_projects.present? %>
					<div class="col-xs-12" style="width: 100%;text-align: center;background-color: #F3E1C2;">
						<strong>No In progress project(s)</strong>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>
<script>
	$(function(){
		$("[data-rel='tooltip']").tooltip();
	})
</script>

app/views/projects/pending_proposed_projects.html.erb
<div class="row-fluid">
	<div class="span3">
		<%= render_panel(current_user.role) %>
	</div>

	<div class="span9"  style="margin-top: 40px;">
		<div class="row">
			<div class="col-xs-12">
				<div class="table-header">
					Projects seeking approval
				</div>
				<div class="table-responsive">
					<div id="sample-table-2_wrapper" class="dataTables_wrapper" role="grid">
						<table id="sample-table-2" class="table table-striped table-bordered table-hover dataTable" aria-describedby="sample-table-2_info">
							<thead>
								<tr role="row">
									<th class="sorting" role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1" aria-label="Domain: activate to sort column ascending" style="width: 80px;">S. No.</th>
									<th class="sorting" role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1" aria-label="Domain: activate to sort column ascending" style="width: 150px;">Issue Title</th>
									<th class="sorting" role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1" aria-label="Price: activate to sort column ascending" style="width: 108px;">Description</th>
									<th class="hidden-480 sorting" role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1" aria-label="Clicks: activate to sort column ascending" style="width: 118px;">Area</th>
									<th class="sorting" role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1" aria-label="Update: activate to sort column ascending" style="width: 178px;">Area Code</th>
									<th class="hidden-480 sorting" role="columnheader" tabindex="0" aria-controls="sample-table-2" rowspan="1" colspan="1" aria-label="Status: activate to sort column ascending" style="width: 145px;">Estd. Cost</th>
									<th class="sorting_disabled" role="columnheader" rowspan="1" colspan="1" aria-label="" style="width: 156px;"></th>
								</tr>
							</thead>
							<tbody role="alert" aria-live="polite" aria-relevant="all">
								<% @pending_proposed_projects.each_with_index do |iss,i| %>
									<tr>
										<% interested_ngos = iss.users.where(role: "NGO").to_a.map{|x| [x.name, x.id]} %>
										<td><%= i + 1 %></td>
										<td><%= iss.issue_title %></td>
										<td><%= iss.issue_description %></td>
										<td><%= iss.issue_area %></td>
										<td><%= iss.issue_area_code %></td>
										<td><%= iss.project_est_cost %> INR </td>
										<td>
											<div class="visible-md visible-lg hidden-sm hidden-xs btn-group">
												<button class="btn btn-xs btn-success" onclick="approveProject(<%= iss.id %>, <%= iss.project_est_cost %>, <%= @avl_social_fund%>);" data-rel="tooltip" title="" data-original-title="Approve Project"><i class="icon-ok bigger-120"></i></button>
												<a href="<%= issue_path(iss.id) %>" class="btn btn-xs btn-info" data-rel="tooltip" title="" data-original-title="Show Project"><i class="icon-eye-open bigger-120"></i></a>
												<% if iss.issue_status == Constants::IssueStatusConstant.all_to_hash[:open] %>
													<button id="int_btn_<%= iss.id%>" class="btn btn-xs btn-danger" onclick="rejectProject(<%= iss.id %>);" data-rel="tooltip" title="" data-original-title="Reject Project"> <i class="icon-trash bigger-120"></i></button>
												<% else %>
													<button id="int_btn_<%= iss.id%>" class="btn btn-xs btn-danger" disabled="disabled"> <i class="icon-trash bigger-120"></i></button>
												<% end %>
											</div>
										</td>
									</tr>
								<% end %>
							</tbody>
						</table>
					</div>
				</div>
				<% unless @pending_proposed_projects.present? %>
					<div class="col-xs-12" style="width: 100%;text-align: center;background-color: #F3E1C2;">
						<strong>No Project(s) to approve</strong>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

<!-- Modal for Approving project upload -->
<div id="approve-project-modal" class="modal hide fade">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>Approve Project</h3>
  </div>
  <div class="modal-body">
    <%= form_tag projects_path, class: "form-horizontal", id: "approveProjectForm" do %>
			<div class="control-group">
				<%= label :ngo, "NGO", class: "control-label" %>
				<div class="controls">
					<%= select_tag(:user_id, options_for_select(User.where(role: "NGO").collect{|x| [x.name, x.id]}), { prompt: "Select NGO"}) %>
				</div>
			</div>

			<div class="control-group">
				<%= label :cost,"Approved Cost", class: "control-label" %>
				<div class="controls">
					<%= text_field_tag :project_actual_cost,nil, onkeypress: "return isNumber(event)" %>
				</div>
			</div>
			<div class="control-group">
				<%= label :duration,"Project Duration", class: "control-label" %>
				<div class="controls">
					<%= text_field_tag :duration %>
				</div>
			</div>
			<%= hidden_field_tag "issue_id", '', id: "issue-id" %>
    <% end %>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn" data-dismiss="modal">Cancel</a>
    <a href="#" class="btn btn-primary" onclick="submitApproveProjectForm();">Approve</a>
  </div>
</div>
<script>
	$(function(){
		$("[data-rel='tooltip']").tooltip();
	});

	function approveProject(issue_id, estCost, avl_fund){
		if (estCost > avl_fund){
			alert("Sorry You Don't Have Sufficient Fund To Pick This Project.");
			return false
		}
		$("#approve-project-modal").modal();
		$("#project_actual_cost").val(estCost);
		$("#issue-id").val(issue_id);
	}

	function rejectProject(issue_id){
		var u_id = <%= current_user.id%>
		$.ajax({ 
			type: "GET",
			dataType: "json",
			data: {issue_id: issue_id, user_id: u_id},
			url: "/projects/reject_project",
			success: function (result) {
				var btn_name = '#int_btn_'+result.iss_id
				$(btn_name).attr("disabled", true);
				$(btn_name).attr("value","Rejected");
			}
		});
	}

	function submitApproveProjectForm(){
		var ngo = $("#assigned_to").val();
		var cost = $("#project_actual_cost").val();
		if(ngo == ''){
			alert("Please select assignee NGO");
			return false;
		}

		if(cost =='' || cost == 0 || cost == '0'){
			alert("Please enter approved cost");
			return false;
		}
		$("#approveProjectForm").submit();
	}
</script>