config/routes.rb
SocialHelpApp::Application.routes.draw do

  resources :proposals
  resources :project_reports, only: [:index, :create] do
    member do
      put 'approve'
      put 'reject'
    end
  end

  resources :issues do
    member do
      put "change_status"
    end
    collection do
      get "interested_ngos"
      get "pending_issues"
      get "completed_issues"
    end
  end

  resources :fiscal_stats
  resources :projects do
    collection do
      get 'completed_projects'
      get 'pending_proposed_projects'
      get 'ongoing_projects'
      get 'reject_project'
      get 'project_reports'
      get 'pending_fund'
      get 'fund_log'
    end
    member do
      get 'close_project'
      post 'release_fund'
    end
  end

  resource :users, only: [:edit] do
    collection do
      patch "update_profile"
      post "change_image"
      get 'user_profile'
    end
  end
  devise_for :users, controllers: {registrations: "sign_up", sessions: "sessions"}

  get "profile" => "users#profile"
  get "dashboard" => "users#dashboard"
  get "my_projects" => "users#my_projects"
  get "welfare_funds" => "users#welfare_funds"
  get "my_proposals" => "proposals#my_proposals"
  get "my_issues" => "issues#my_issues"
  get "donate" => "users#donate"
  post "receive_donation" => "users#receive_donation"
  get "my_donations" => "users#my_donations"
  get "reject_proposal" => "proposals#reject_proposal"
  get "view_donations" => "users#view_donations"
  root to: "users#home"

end

app/views/navs/_analyst_left_panel.html.erb
<div class="sidebar" id="sidebar">

	<ul class="nav nav-list">
		<li id="li_dashboard">
			<a href="/dashboard">
				<i class="icon-dashboard"></i>
				<span class="menu-text"> Dashboard </span>
			</a>
		</li>

		<li>
			<a href="#" class="dropdown-toggle">
				<i class="icon-list"></i>
				<span class="menu-text"> All Issues </span>
				<b class="arrow icon-angle-down"></b>
			</a>
			<ul class="submenu">
				<% Constants::IssueCategoryConstant.to_list.each do |c| %>
					<% cat = c.downcase.strip.split(" ").join("_") %>
					<li id="li_<%= cat %>">
						<a href="/issues?cat=<%= cat %>">
							<i class="icon-double-angle-right"></i>
							<%= c %>
						</a>
					</li>
				<% end %>
			</ul>
		</li>

		<li>
			<a href="#" class="dropdown-toggle">
				<i class="icon-globe"></i>
				<span class="menu-text"> Projects </span>
				<b class="arrow icon-angle-down"></b>
			</a>

			<ul class="submenu">
				<li id="li_on_projects">
					<a href="/projects/ongoing_projects">
						<i class="icon-double-angle-right"></i>
						In Progress
					</a>
				</li>

				<li id="li_comp_projects">
					<a href="/projects/completed_projects">
						<i class="icon-double-angle-right"></i>
						Completed Projects
					</a>
				</li>
			</ul>
		</li>

		<li>
			<a href="#" class="dropdown-toggle">
				<i class="icon-money"></i>
				<span class="menu-text"> Fund </span>
				<b class="arrow icon-angle-down"></b>
			</a>

			<ul class="submenu">
				<li id="li_fund_release">
					<a href="/projects/pending_fund">
						<i class="icon-double-angle-right"></i>
						Allocate Fund
					</a>
				</li>

				<li id="li_fund_log">
					<a href="/projects/fund_log">
						<i class="icon-double-angle-right"></i>
						Fund Log
					</a>
				</li>
			</ul>
		</li>

		<li id="li_donation">
			<a href="/view_donations">
				<i class="icon-money"></i>
				<span class="menu-text"> View Donations </span>
			</a>
		</li>

		<li id="li_welfare-fund">
			<a href="/welfare_funds">
				<i class="icon-group"></i>
				<span class="menu-text"> Social Welfare Fund </span>
			</a>
		</li>

		<li id="li_profile">
			<a href="/profile?nav=profile">
				<i class="icon-picture"></i>
				<span class="menu-text"> Profile </span>
			</a>
		</li>
	</ul>

	<div class="sidebar-collapse" id="sidebar-collapse">
		<i class="icon-double-angle-left" data-icon1="icon-double-angle-left" data-icon2="icon-double-angle-right"></i>
	</div>

</div>
<script>
	<% if params[:nav].present? %>
		var nav = "<%= params[:nav] %>"
		$("#li_" + nav).addClass("active");
	<% elsif params[:cat].present? %>
		var category = "<%= params[:cat] %>"
		var li = $("#li_" + category);
		li.addClass("active");
		li.parent().closest("li").addClass("open").addClass("active");
	<% else %>
		$("#li_dashboard").addClass("active");
	<% end %>
</script>

app/views/navs/_corp_left_panel.html.erb
<div class="sidebar" id="sidebar">

	<ul class="nav nav-list">
		<li id="li_dashboard">
			<a href="/dashboard">
				<i class="icon-dashboard"></i>
				<span class="menu-text"> Dashboard </span>
			</a>
		</li>

		<li id="li_add_fiscal_stat">
			<a href="<%= new_fiscal_stat_path%>">
				<i class="icon-list"></i>
				<span class="menu-text"> Add Financial Details </span>
			</a>
		</li>

		<li id="li_list_fiscal_stats">
			<a href="<%= fiscal_stats_path%>">
				<i class="icon-plus-sign"></i>
				<span class="menu-text">View Financial Stats </span>
			</a>
		</li>
		
		<li>
			<a href="#" class="dropdown-toggle">
				<i class="icon-dollar"></i>
				<span class="menu-text"> Donations </span>
				<b class="arrow icon-angle-down"></b>
			</a>
			<ul class="submenu">
				<li id="li_donate">
					<a href="/donate">
						<i class="icon-double-angle-right"></i>
						Donete Now
					</a>
				</li>

				<li id="li_my_donations">
					<a href="/my_donations">
						<i class="icon-double-angle-right"></i>
						My Donations
					</a>
				</li>
			</ul>
		</li>

		<li id="li_profile">
			<a href="/profile">
				<i class="icon-plus-sign"></i>
				<span class="menu-text"> View Profile </span>
			</a>
		</li>

	</ul>

	<div class="sidebar-collapse" id="sidebar-collapse">
		<i class="icon-double-angle-left" data-icon1="icon-double-angle-left" data-icon2="icon-double-angle-right"></i>
	</div>

</div>
<script>
	<% if params[:nav].present? %>
		var nav = "<%= params[:nav] %>"
		$("#li_" + nav).addClass("active");
	<% elsif params[:cat].present? %>
		var category = "<%= params[:cat] %>"
		var li = $("#li_" + category);
		li.addClass("active");
		li.parent().closest("li").addClass("open").addClass("active");
	<% else %>
		$("#li_dashboard").addClass("active");
	<% end %>
</script>

app/views/navs/_donor_left_panel.html.erb
<div class="sidebar" id="sidebar">

	<ul class="nav nav-list">
		<li id="li_dashboard">
			<a href="/dashboard">
				<i class="icon-dashboard"></i>
				<span class="menu-text"> Dashboard </span>
			</a>
		</li>

		<li>
			<a href="#" class="dropdown-toggle">
				<i class="icon-dollar"></i>
				<span class="menu-text"> Donations </span>
				<b class="arrow icon-angle-down"></b>
			</a>
			<ul class="submenu">
				<li id="li_donate">
					<a href="/donate">
						<i class="icon-double-angle-right"></i>
						Donete Now
					</a>
				</li>

				<li id="li_my_donations">
					<a href="/my_donations">
						<i class="icon-double-angle-right"></i>
						My Donations
					</a>
				</li>
			</ul>
		</li>

		<li id="li_profile">
			<a href="/profile">
				<i class="icon-picture"></i>
				<span class="menu-text"> Profile </span>
			</a>
		</li>
		
	</ul>

	<div class="sidebar-collapse" id="sidebar-collapse">
		<i class="icon-double-angle-left" data-icon1="icon-double-angle-left" data-icon2="icon-double-angle-right"></i>
	</div>

</div>
<script>
	<% if params[:nav].present? %>
		var nav = "<%= params[:nav] %>"
		$("#li_" + nav).addClass("active");
	<% elsif params[:cat].present? %>
		var category = "<%= params[:cat] %>"
		var li = $("#li_" + category);
		li.addClass("active");
		li.parent().closest("li").addClass("open").addClass("active");
	<% else %>
		$("#li_dashboard").addClass("active");
	<% end %>
</script>

app/views/navs/_inspector_left_panel.html.erb
<div class="sidebar" id="sidebar">

	<ul class="nav nav-list">
		<li id="li_dashboard">
			<a href="/dashboard">
				<i class="icon-dashboard"></i>
				<span class="menu-text"> Dashboard </span>
			</a>
		</li>

		<li>
			<a href="#" class="dropdown-toggle">
				<i class="icon-text-width"></i>
				<span class="menu-text"> All Issues </span>
				<b class="arrow icon-angle-down"></b>
			</a>
			<ul class="submenu">
				<% Constants::IssueStatusConstant.to_list.each do |c| %>
					<% cat = c.downcase.strip.split(" ").join("_") %>
					<li id="li_<%= cat %>">
						<a href="/issues?cat=<%= cat %>">
							<i class="icon-double-angle-right"></i>
							<%= c %>
						</a>
					</li>
				<% end %>
			</ul>
		</li>

		<li>
			<a href="#" class="dropdown-toggle">
				<i class="icon-desktop"></i>
				<span class="menu-text"> Project Reports </span>
				<b class="arrow icon-angle-down"></b>
			</a>

			<ul class="submenu">
				<li id="li_pending_reports">
					<a href="/project_reports?cat=pending_reports">
						<i class="icon-double-angle-right"></i>
						Pending Reports
					</a>
				</li>

				<li id="li_approved_reports">
					<a href="/project_reports?cat=approved_reports">
						<i class="icon-double-angle-right"></i>
						Approved Reports
					</a>
				</li>

				<li id="li_rejected_reports">
					<a href="/project_reports?cat=rejected_reports">
						<i class="icon-double-angle-right"></i>
						Rejected Reports
					</a>
				</li>
			</ul>
		</li>

		<li id="li_comp_projects">
			<a href="/projects/completed_projects?nav=comp_projects">
				<i class="icon-list"></i>
				<span class="menu-text"> Completed Projects </span>
			</a>
		</li>

		<li id="li_profile">
			<a href="/profile?nav=profile">
				<i class="icon-edit"></i>
				<span class="menu-text"> Profile </span>
			</a>
		</li>
	</ul>

	<div class="sidebar-collapse" id="sidebar-collapse">
		<i class="icon-double-angle-left" data-icon1="icon-double-angle-left" data-icon2="icon-double-angle-right"></i>
	</div>

</div>
<script>
	<% if params[:nav].present? %>
		var nav = "<%= params[:nav] %>"
		$("#li_" + nav).addClass("active");
	<% elsif params[:cat].present? %>
		var category = "<%= params[:cat] %>"
		var li = $("#li_" + category);
		li.addClass("active");
		li.parent().closest("li").addClass("open").addClass("active");
	<% else %>
		$("#li_dashboard").addClass("active");
	<% end %>
</script>

app/views/navs/_ngo_left_panel.html.erb
<link rel="stylesheet" href="/assets/ace.min.css">
<link rel="stylesheet" href="/assets/ace-rtl.min.css">
<link rel="stylesheet" href="/assets/ace-skins.min.css">

<div class="sidebar" id="sidebar">

	<ul class="nav nav-list">
		<li id="li_dashboard">
			<a href="/dashboard">
				<i class="icon-dashboard"></i>
				<span class="menu-text"> Dashboard </span>
			</a>
		</li>

		<li id="li_all_projects">
			<a href="/issues">
				<i class="icon-list"></i>
				<span class="menu-text"> All Issues </span>
			</a>
		</li>

		<li id="li_add_issue">
			<a href="/issues/new">
				<i class="icon-plus-sign"></i>
				<span class="menu-text"> Add New Issue </span>
			</a>
		</li>

		<li id="li_my_issues">
			<a href="/my_issues">
				<i class="icon-download-alt"></i>
				<span class="menu-text"> Issues By Me </span>
			</a>
		</li>

		<li>
			<a href="#" class="dropdown-toggle">
				<i class="icon-globe"></i>
				<span class="menu-text"> My Projects </span>
				<b class="arrow icon-angle-down"></b>
			</a>

			<ul class="submenu">
				<li id="li_in_progress">
					<a href="/my_projects?cat=in_progress">
						<i class="icon-double-angle-right"></i>
						In Progress
					</a>
				</li>

				<li id="li_completed_projects">
					<a href="/my_projects?cat=completed_projects">
						<i class="icon-double-angle-right"></i>
						Completed Projects
					</a>
				</li>
			</ul>
		</li>

		<li id="li_my_proposal">
			<a href="/my_proposals">
				<i class="icon-download-alt"></i>
				<span class="menu-text"> My Proposals </span>
			</a>
		</li>

		<li id="li_profile">
			<a href="/profile">
				<i class="icon-picture"></i>
				<span class="menu-text"> Profile </span>
			</a>
		</li>
	</ul>

	<div class="sidebar-collapse" id="sidebar-collapse">
		<i class="icon-double-angle-left" data-icon1="icon-double-angle-left" data-icon2="icon-double-angle-right"></i>
	</div>

</div>
<script>
	<% if params[:nav].present? %>
		var nav = "<%= params[:nav] %>"
		$("#li_" + nav).addClass("active");
	<% elsif params[:cat].present? %>
		var category = "<%= params[:cat] %>"
		var li = $("#li_" + category);
		li.addClass("active");
		li.parent().closest("li").addClass("open").addClass("active");
	<% else %>
		$("#li_dashboard").addClass("active");
	<% end %>
</script>

app/views/navs/_socialist_left_panel.html.erb
<div class="sidebar" id="sidebar">

	<ul class="nav nav-list">
		<li id="li_dashboard">
			<a href="/dashboard">
				<i class="icon-dashboard"></i>
				<span class="menu-text"> Dashboard </span>
			</a>
		</li>

		<li id="li_all_projects">
			<a href="/issues">
				<i class="icon-list"></i>
				<span class="menu-text"> All Issues </span>
			</a>
		</li>

		<li id="li_my_issues">
			<a href="/my_issues">
				<i class="icon-download-alt"></i>
				<span class="menu-text"> Issues By Me </span>
			</a>
		</li>

		<li id="li_ongoing_projects">
			<a href="/projects/ongoing_projects?spec=true">
				<i class="icon-play"></i>
				<span class="menu-text"> Ongoing Projects </span>
			</a>
		</li>

		<li id="li_completed_projects">
			<a href="/projects/completed_projects?spec=true">
				<i class="icon-stop"></i>
				<span class="menu-text"> Completed Projects </span>
			</a>
		</li>

		<li id="li_add_issue">
			<a href="/issues/new">
				<i class="icon-plus-sign"></i>
				<span class="menu-text"> Add New Issue </span>
			</a>
		</li>

		<li>
			<a href="#" class="dropdown-toggle">
				<i class="icon-dollar"></i>
				<span class="menu-text"> Donations </span>
				<b class="arrow icon-angle-down"></b>
			</a>
			<ul class="submenu">
				<li id="li_donate">
					<a href="/donate">
						<i class="icon-double-angle-right"></i>
						Donete Now
					</a>
				</li>

				<li id="li_my_donations">
					<a href="/my_donations">
						<i class="icon-double-angle-right"></i>
						My Donations
					</a>
				</li>
			</ul>
		</li>

		<li id="li_profile">
			<a href="/profile">
				<i class="icon-picture"></i>
				<span class="menu-text"> Profile </span>
			</a>
		</li>
		
	</ul>

	<div class="sidebar-collapse" id="sidebar-collapse">
		<i class="icon-double-angle-left" data-icon1="icon-double-angle-left" data-icon2="icon-double-angle-right"></i>
	</div>

</div>
<script>
	<% if params[:nav].present? %>
		var nav = "<%= params[:nav] %>"
		$("#li_" + nav).addClass("active");
	<% elsif params[:cat].present? %>
		var category = "<%= params[:cat] %>"
		var li = $("#li_" + category);
		li.addClass("active");
		li.parent().closest("li").addClass("open").addClass("active");
	<% else %>
		$("#li_dashboard").addClass("active");
	<% end %>
</script>