config/routes.rb
SocialHelpApp::Application.routes.draw do

  resources :proposals
  resources :project_reports, only: [:index, :create] do
    member do
      put 'approve'
      put 'reject'
    end
  end

  resources :issues do
    member do
      put "change_status"
    end
    collection do
      get "interested_ngos"
      get "pending_issues"
      get "completed_issues"
    end
  end

  resources :fiscal_stats
  resources :projects do
    collection do
      get 'completed_projects'
      get 'pending_proposed_projects'
      get 'ongoing_projects'
      get 'reject_project'
      get 'project_reports'
      get 'pending_fund'
      get 'fund_log'
    end
    member do
      get 'close_project'
      post 'release_fund'
    end
  end

  resource :users, only: [:edit] do
    collection do
      patch "update_profile"
      post "change_image"
      get 'user_profile'
    end
  end
  devise_for :users, controllers: {registrations: "sign_up", sessions: "sessions"}

  get "profile" => "users#profile"
  get "dashboard" => "users#dashboard"
  get "my_projects" => "users#my_projects"
  get "welfare_funds" => "users#welfare_funds"
  get "my_proposals" => "proposals#my_proposals"
  get "my_issues" => "issues#my_issues"
  get "donate" => "users#donate"
  post "receive_donation" => "users#receive_donation"
  get "my_donations" => "users#my_donations"
  get "reject_proposal" => "proposals#reject_proposal"
  get "view_donations" => "users#view_donations"
  root to: "users#home"

end

app/models/proposal.rb
class Proposal < ActiveRecord::Base
	belongs_to :issue
	belongs_to :user
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  before_action :set_proposal, only: [:show, :edit, :update, :destroy]

  # GET /proposals
  # GET /proposals.json
  def index
    @proposals = Proposal.where(issue_id: params[:issue_id])
    issue = Issue.find_by(id: params[:issue_id])
    fund = SocialFund.order("fiscal_year DESC").first
    if fund.present?
      @avl_cat_fund = issue.category == "Any Cause" ? fund.fund_for_others : fund.send("fund_for_#{issue.category.downcase}")
      if @avl_cat_fund == 0 && fund.fund_for_others > 0
        @avl_cat_fund = fund.fund_for_others
      end
    else
      @avl_cat_fund = 0
    end 
    @project = Project.find_by(issue_id: params[:issue_id])
  end

  # GET /proposals/1
  # GET /proposals/1.json
  def show
    @issue = Proposal.where(id: params[:id]).first
  end

  # GET /proposals/new
  def new
    @proposal = Proposal.new
  end

  # GET /proposals/1/edit
  def edit
    @issue = Proposal.where(id: params[:id]).first
  end

  # POST /proposals
  # POST /proposals.json
  def create
    @proposal = Proposal.new(proposal_params)
    @proposal.user_id = current_user.id
    @proposal.status = Constants::ProposalStatusConstant.all_to_hash[:pending]
    if @proposal.save
      issue = Issue.where(id: params[:proposal][:issue_id]).first
      current_user.issues << issue
      redirect_to :action => "my_proposals" 
    end
  end

  # PATCH/PUT /proposals/1
  # PATCH/PUT /proposals/1.json
  def update
    @proposal.update(proposal_params)
    redirect_to :action => "my_proposals"
  end

  # DELETE /proposals/1
  # DELETE /proposals/1.json
  def destroy
    @proposal.destroy
    respond_to do |format|
      format.html { redirect_to proposals_url }
      format.json { head :no_content }
    end
  end

  # proposals for current user
  def my_proposals
    @proposals = Proposal.where(user_id: current_user.id)
    params[:nav] = "my_proposal"
    render 'index'
  end

  def reject_proposal
    proposal = Proposal.where(id: params[:id]).first
    proposal.update_attributes(status: Constants::ProposalStatusConstant.all_to_hash[:rejected])
    render json: {status: 500, prop_id: params[:id]}
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proposal
      @proposal = Proposal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def proposal_params
      params.require(:proposal).permit(:issue_id, :proposed_cost, :proposed_duration, :desc, :status, :user_id)
    end
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/views/proposals/_form.html.erb
<%= form_for(@proposal) do |f| %>
  <% if @proposal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@proposal.errors.count, "error") %> prohibited this proposal from being saved:</h2>

      <ul>
      <% @proposal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/proposals/edit.html.erb
<div class="row-fluid">
	<div class="span3">
		<%= render_panel(current_user.role) %>
	</div>

	<div class="panel-sign-in span9"  style="margin-top: 40px;">
		<div class="panel-heading-sign-in">
			<h4>Edit Proposal</h4>
		</div>
		<div class="panel-body-sign-in">
			<div class="form-wrapper">
				<%= form_for @proposal, html: {class: "form-horizontal", method: :put} do |f| %>
					<div class="control-group">
						<%= label :proposed_cost, "Proposed Cost", class: "control-label" %>
						<div class="controls">
							<%= f.text_field :proposed_cost, style: "width: 350px;"%>
						</div>
					</div>
				
					<div class="control-group">
						<%= label :proposed_duration, "Proposed Duration", class: "control-label" %>
						<div class="controls">
							<%= f.text_field :proposed_duration, style: "width: 350px;"%>
						</div>
					</div>

					<div class="control-group">
						<%= label :desc, "Issue Description", class: "control-label" %>
						<div class="controls">
							<%= f.text_area :desc, style: "width: 350px;"%>
						</div>
					</div>

					<div class="control-group">
						<div class="controls">
							<button type="submit" class="btn btn-warning">Update Proposal</button>
						</div>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/proposals/index.html.erb
<div class="row-fluid">
  <div class="span3">
    <%= render_panel(current_user.role) %>
  </div>

  <div class="span9"  style="margin-top: 40px;">
    <div class="row">
      <div class="col-xs-12">
        <div class="table-header">
          My Proposals
        </div>
        <div class="table-responsive">
          <div id="sample-table-2_wrapper" class="dataTables_wrapper" role="grid">
            <table id="sample-table-2" class="table table-striped table-bordered table-hover dataTable" aria-describedby="sample-table-2_info">
              <thead>
                <tr role="row">
                  <th class="sorting" role="columnheader" tabindex="0" style="width: 80px;">S. No.</th>
                  <th class="sorting" role="columnheader" tabindex="0" style="width: 150px;">Issue Name</th>
                  <th class="sorting" role="columnheader" tabindex="0" style="width: 130px;">Proposed Cost</th>
                  <th class="sorting" role="columnheader" tabindex="0" style="width: 138px;">Duration</th>
                  <th class="sorting" role="columnheader" tabindex="0" style="width: 120px;">Description</th>
                  <th class="sorting" role="columnheader" tabindex="0" style="width: 120px;"><%= current_user.role == "Analyst" ? "Proposed By" : "Status"%></th>
                  <th class="sorting_disabled" role="columnheader" style="width: 156px;"></th>
                </tr>
              </thead>
              <tbody role="alert" aria-live="polite" aria-relevant="all">
                <% @proposals.each_with_index do |prop,i| %>
                  <tr>
                    <td><%= i + 1 %></td>
                    <td><%= prop.issue.issue_title %></td>
                    <td><%= prop.proposed_cost %></td>
                    <td><%= prop.proposed_duration %> Months</td>
                    <td><%= prop.desc %></td>
                    <td>
                      <%if current_user.role == "Analyst"%>
                        <%= prop.user.name%>
                      <%else%>
                        <%= prop.status%>
                      <%end%>
                    </td>
                    <td>
                      <div class="visible-md visible-lg hidden-sm hidden-xs btn-group">
                        <%if current_user.role == "Analyst"%>
                          <%if @project.present? || prop.status == "Rejected"%>
                            <button class="btn btn-xs btn-success" disabled="disabled" data-rel="tooltip" title=""><i class="icon-ok bigger-120"></i></button>
                            <button class="btn btn-xs btn-danger proposal_<%= prop.id%>" disabled="disabled" onclick="rejectProposal(<%= prop.id%>);" data-rel="tooltip" title=""><i class="icon-minus bigger-120"></i>
                            </button>                                               
                          <%else%>
                            <button class="btn btn-xs btn-success proposal_<%= prop.id%>" onclick="approveProposal(<%= @avl_cat_fund%>, <%= params[:issue_id]%>, <%= prop.proposed_cost%>, <%= prop.proposed_duration%>, <%= prop.user_id%>, <%= prop.id%>);" data-rel="tooltip" title="" data-original-title="Approve Proposal"><i class="icon-ok bigger-120"></i></button>
                            <button class="btn btn-xs btn-danger proposal_<%= prop.id%>" onclick="rejectProposal(<%= prop.id%>);" data-rel="tooltip" title="" data-original-title="Reject Proposal"><i class="icon-minus bigger-120"></i></button>                                                       
                          <%end%>
                        <%elsif current_user.role == "NGO" %>
                          <% already_present = Project.find_by(issue_id: prop.issue_id)%>
                          <%if already_present.present? %>
                            <button class="btn btn-xs btn-danger" disabled="disabled" data-rel="tooltip" title="" data-original-title="Can't Edit Now"><i class="icon-edit bigger-120"></i></button>                    
                          <%else%>
                            <a href="<%= edit_proposal_path(prop) %>" class="btn btn-xs btn-danger"  data-rel="tooltip" title="" data-original-title="Edit Proposal"><i class="icon-edit bigger-120"></i></a>
                          <%end%>
                        <%end%>
                      </div> 
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
        <% unless @proposals.present? %>
          <div class="col-xs-12" style="width: 100%;text-align: center;background-color: #F3E1C2;">
            <strong>No Proposal(s)</strong>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>


<script>
  $(function(){
    $("[data-rel='tooltip']").tooltip();
  });

  function approveProposal(avl_fund, issue_id, prCost, prDuration, prUserId, prId){
    if (prCost > avl_fund){
      alert("Sorry You Don't Have Sufficient Fund To Allocate This Project.");
      return false;
    }
    $.ajax({
      type: "POST",
      dataType: "json",
      data: {
        project: {
          issue_id: issue_id,
          project_actual_cost: prCost,
          project_duration: prDuration,
          user_id: prUserId,
          prop_id: prId
        },
        authenticity_token: "<%= form_authenticity_token %>"
      },
      url: '/projects',
      success: function(result){
        var btn_name = '.proposal_'+result.prop_id
        $(btn_name).attr("disabled", true);
        $('.btn-xs').attr("disabled", true);
        alert('Proposal Approved And Project Assigned Successfully');
      }
    });

  }

  function rejectProposal(prop_id){
    $.ajax({
      type: "GET",
      dataType: "json",
      data: {id: prop_id},
      url: "/reject_proposal",
      success: function(result){
        var btn_name = '.proposal_'+result.prop_id
        $(btn_name).attr("disabled", true);
      }
    });
  }

</script>

app/views/proposals/new.html.erb
<h1>New proposal</h1>

<%= render 'form' %>

<%= link_to 'Back', proposals_path %>

app/views/proposals/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_proposal_path(@proposal) %> |
<%= link_to 'Back', proposals_path %>